### ISSUE TITLE
Interinstitutional Agreement - decentralised

### ISSUE THREAD

**Issue by StefanJahnke** [erasmus-without-paper/ewp-wp4-use-cases#1]
WP2 recommends strongly against a central web application with user management system. It will enhance the security risk and potentially disqualified the EWP architecture for both the European Commission (see Desk research - meeting with Mobility Tool+ colleagues from the EC) and Higher Education Institutions concerned about security.

The overview of participating institutions should be handled by the EWP consortium (managing the registry) for the moment.

**Comment by wrygiel** [comment]
I haven't seen your topic posted here before and started a duplicate here:

https://github.com/erasmus-without-paper/general-issues/issues/12

I will close this one.
