### ISSUE TITLE
IIAS API vs Institutions API and Departments API

### ISSUE THREAD

**Issue by pleys** [erasmus-without-paper/ewp-wp4-use-cases#4]
We will need to agree on what info is part of the IIAS API and what info is part of the Institutions API/Departments API

**Comment by wrygiel** [comment]
I guess that @erasmus-without-paper/wp3 will deal with it shortly. As far as I know, the currently posted schemas are early drafts.

**Comment by pleys** [comment]
@wrygiel Ok thanks. They should certainly include @StefanJahnke and myself (@pleys) in this discussion as well.
